# Helm values for cert-manager chart version 1.12.0
# Configures certificate management for Mint Clone application

nameOverride: "mint-cert-manager"
fullnameOverride: "mint-cert-manager"

# Install Custom Resource Definitions
installCRDs: true

# Number of controller replicas for high availability
replicaCount: 2

image:
  repository: quay.io/jetstack/cert-manager-controller
  tag: v1.12.0
  pullPolicy: IfNotPresent

# Resource allocation for cert-manager controller
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

# Prometheus monitoring configuration
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    namespace: monitoring
    interval: "30s"

# Webhook configuration for validation
webhook:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

# CA injector configuration for certificate injection
cainjector:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

# Pod security context
podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
  runAsNonRoot: true

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Service account configuration for AWS IAM integration
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ${CERT_MANAGER_IAM_ROLE}

# Cluster issuers configuration for Let's Encrypt
clusterIssuers:
  letsencrypt-prod:
    enabled: true
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@mintclone.com
    privateKeySecretRef:
      name: letsencrypt-prod-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx