openapi: 3.0.3
info:
  title: Mint Clone Accounts Service API
  description: |
    API specification for the Accounts Service, handling financial account management,
    Plaid integration, and account synchronization operations.
  version: 1.0.0
  contact:
    name: Mint Clone Development Team
    email: dev-team@mintclone.com

servers:
  - url: /api/v1
    description: Production server
  - url: /api/v1/staging
    description: Staging server

security:
  - bearerAuth: []
  - oauth2: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /auth/oauth2/authorize
          tokenUrl: /auth/oauth2/token
          scopes:
            accounts:read: Read account information
            accounts:write: Modify account information

  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique account identifier
        userId:
          type: string
          format: uuid
          description: Owner's user ID
        plaidAccountId:
          type: string
          description: Plaid account identifier
        institutionId:
          type: string
          description: Financial institution identifier
        name:
          type: string
          description: Account display name
        type:
          type: string
          enum: [CHECKING, SAVINGS, CREDIT, INVESTMENT]
          description: Account type
        balance:
          type: number
          format: double
          description: Current account balance
        currency:
          type: string
          default: USD
          description: Account currency code
        lastSynced:
          type: string
          format: date-time
          description: Last successful sync timestamp
        status:
          type: string
          enum: [active, inactive, error]
          description: Account status
        syncStatus:
          type: string
          enum: [success, pending, error]
          description: Last sync attempt status
        errorCode:
          type: string
          description: Error code if sync failed
        errorMessage:
          type: string
          description: User-friendly error message

    PlaidLinkRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          format: uuid
          description: User requesting Plaid link token

    PlaidLinkResponse:
      type: object
      properties:
        linkToken:
          type: string
          description: Plaid link token for client-side integration
        expiration:
          type: string
          format: date-time
          description: Link token expiration timestamp

    AccountCreationRequest:
      type: object
      required:
        - userId
        - publicToken
        - institutionId
      properties:
        userId:
          type: string
          format: uuid
          description: User creating the account
        publicToken:
          type: string
          description: Plaid public token from link flow
        institutionId:
          type: string
          description: Financial institution identifier

    AccountSyncRequest:
      type: object
      required:
        - accountId
      properties:
        accountId:
          type: string
          format: uuid
          description: Account to synchronize

    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: User-friendly error message
        details:
          type: object
          description: Additional error details
        timestamp:
          type: string
          format: date-time
          description: Error timestamp

paths:
  /plaid/link:
    post:
      summary: Initialize Plaid Link flow
      description: Creates a Plaid link token for connecting financial institutions
      operationId: createPlaidLinkToken
      tags: [Plaid Integration]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaidLinkRequest'
      responses:
        '200':
          description: Link token created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaidLinkResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error
      x-rateLimit:
        limit: 5
        period: 60

  /plaid/complete:
    post:
      summary: Complete Plaid account linking
      description: Exchanges public token and creates linked accounts
      operationId: completePlaidLink
      tags: [Plaid Integration]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreationRequest'
      responses:
        '201':
          description: Accounts created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          description: Invalid request parameters
        '401':
          description: Unauthorized
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error
      x-rateLimit:
        limit: 5
        period: 60

  /accounts:
    get:
      summary: List user accounts
      description: Retrieves all accounts for authenticated user
      operationId: listAccounts
      tags: [Account Management]
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Items per page
      responses:
        '200':
          description: Account list retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Account'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      pages:
                        type: integer
                      current:
                        type: integer
        '401':
          description: Unauthorized
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error
      x-rateLimit:
        limit: 30
        period: 60

  /accounts/{id}/sync:
    post:
      summary: Synchronize account
      description: Initiates account data synchronization with 30-second timeout
      operationId: syncAccount
      tags: [Account Management]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Account ID to synchronize
      responses:
        '200':
          description: Account synchronized successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '408':
          description: Sync timeout exceeded
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error
      x-rateLimit:
        limit: 10
        period: 60

tags:
  - name: Plaid Integration
    description: Endpoints for Plaid service integration
  - name: Account Management
    description: Account management operations

x-performance:
  caching:
    - path: /accounts
      ttl: 300
  monitoring:
    - metric: response_time
      threshold: 3000
    - metric: error_rate
      threshold: 0.01