global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.aws.com:587
  smtp_from: alerts@mintclone.com
  smtp_auth_username: ${SMTP_USER}
  smtp_auth_password: ${SMTP_PASSWORD}
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  cluster_name: mint-clone-prod

route:
  group_by: ['alertname', 'cluster', 'service', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: team-email
  routes:
    - match:
        severity: critical
      receiver: team-pager
      group_wait: 15s
      repeat_interval: 1h
      continue: true

    - match:
        severity: warning
      receiver: team-email
      group_wait: 1m
      repeat_interval: 4h

    - match_re:
        service: ".*auth.*|.*payment.*"
      receiver: security-team
      group_wait: 30s
      repeat_interval: 2h

receivers:
  - name: team-email
    email_configs:
      - to: team@mintclone.com
        send_resolved: true
        html: '{{ template "email.default.html" . }}'
        headers:
          Subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'

  - name: team-pager
    email_configs:
      - to: oncall@mintclone.com
        send_resolved: true
        html: '{{ template "email.critical.html" . }}'
    pagerduty_configs:
      - service_key: ${PAGERDUTY_KEY}
        send_resolved: true
        severity: '{{ .CommonLabels.severity }}'
        description: '{{ .CommonLabels.description }}'
        client: AlertManager
        client_url: '{{ .ExternalURL }}'

  - name: security-team
    email_configs:
      - to: security@mintclone.com
        send_resolved: true
        html: '{{ template "email.security.html" . }}'
    pagerduty_configs:
      - service_key: ${SECURITY_PAGERDUTY_KEY}
        send_resolved: true
        severity: high
        description: 'Security Alert: {{ .CommonLabels.description }}'

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'cluster', 'service']

  - source_match:
      severity: warning
    target_match:
      severity: info
    equal: ['alertname', 'cluster', 'service']

templates:
  - /etc/alertmanager/templates/*.tmpl