platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MintClone' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: true,
    fabric_enabled: true,
    app_path: "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'React', path: '../node_modules/react-native/'
  pod 'React-Core', path: '../node_modules/react-native/React'
  pod 'react-native-plaid-link-sdk', '~> 10.0.0'
  pod 'RNReanimated', '~> 3.0.0'
  pod 'RNSVG', '~> 13.0.0'

  target 'MintCloneTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'YES'
        config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['ENABLE_TESTABILITY'] = 'NO'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 's'
        config.build_settings['LLVM_LTO'] = 'YES'
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_LDFLAGS'] << '-ObjC'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings.delete 'ARCHS'
        config.build_settings['ENABLE_APP_TRANSPORT_SECURITY'] = 'YES'
        config.build_settings['ENABLE_SSL_PINNING'] = 'YES'
        config.build_settings['ENABLE_SECURITY_AUDIT'] = 'YES'
        config.build_settings['ENABLE_MEMORY_OPTIMIZATION'] = 'YES'
        config.build_settings['ENABLE_PERFORMANCE_LOGGING'] = 'YES'
        config.build_settings['ENABLE_CRASH_REPORTING'] = 'YES'
      end
    end
  end
end