apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: mint-clone
  labels:
    app: mint-clone
    component: database
    environment: production
  annotations:
    rotation-schedule: "30d"
    last-rotated: "2024-01-01T00:00:00Z"
    encryption: aws-kms
type: Opaque
data:
  postgres-user: UE9TVEdSRVNfVVNFUg==
  postgres-password: UE9TVEdSRVNfUEFTU1dPUkQ=
  postgres-connection-string: cG9zdGdyZXM6Ly9wb3N0Z3Jlc191c2VyOnBvc3RncmVzX3Bhc3N3b3JkQHBvc3RncmVzLW1pbnQtY2xvbmU6NTQzMi9taW50X2Nsb25l
  mongodb-user: TU9OR09EQl9VU0VS
  mongodb-password: TU9OR09EQl9QQVNTV09SRA==
  mongodb-connection-string: bW9uZ29kYitzcnY6Ly9tb25nb2RiX3VzZXI6bW9uZ29kYl9wYXNzd29yZEBtb25nb2RiLW1pbnQtY2xvbmU6MjcwMTcvbWludF9jbG9uZQ==
  redis-password: UkVESVNfUEFTU1dPUkQ=
  redis-connection-string: cmVkaXM6Ly9yZWRpc19wYXNzd29yZEByZWRpcy1taW50LWNsb25lOjYzNzk=
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: mint-clone
  labels:
    app: mint-clone
    component: external-services
    environment: production
  annotations:
    rotation-schedule: "90d"
    last-rotated: "2024-01-01T00:00:00Z"
    encryption: aws-kms
type: Opaque
data:
  plaid-client-id: UExBSURfQ0xJRU5UX0lE
  plaid-secret: UExBSURfU0VDUkVU
  plaid-environment: cHJvZHVjdGlvbg==
  aws-access-key: QVdTX0FDQ0VTU19LRVk=
  aws-secret-key: QVdTX1NFQ1JFVF9LRVk=
  aws-region: dXMtZWFzdC0x
  aws-kms-key-arn: YXJuOmF3czprbXM6dXMtZWFzdC0xOjEyMzQ1Njc4OTAxMjprZXkvYWJjZGVmMTIzNA==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: mint-clone
  labels:
    app: mint-clone
    component: auth
    environment: production
  annotations:
    rotation-schedule: "60d"
    last-rotated: "2024-01-01T00:00:00Z"
    encryption: aws-kms
type: Opaque
data:
  jwt-secret: SldUX1NFQ1JFVF9LRVk=
  refresh-token-secret: UkVGUkVTSF9UT0tFTl9TRUNSRVRfS0VZ
  jwt-expiration: MTVt
  refresh-token-expiration: N2Q=
  jwt-algorithm: SFMyNTY=
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
  namespace: mint-clone
  labels:
    app: mint-clone
    component: security
    environment: production
  annotations:
    rotation-schedule: "180d"
    last-rotated: "2024-01-01T00:00:00Z"
    encryption: aws-kms
type: Opaque
data:
  data-encryption-key: REFUQV9FTkNSWVBUSU9OX0tFWQ==
  kms-key-id: a21zLWtleS1pZA==
  encryption-algorithm: QUVTLTI1Ni1HQ00=
  key-rotation-policy: eyJhdXRvbWF0aWNSb3RhdGlvbiI6dHJ1ZSwicm90YXRpb25QZXJpb2QiOiIxODBkIn0=