apiVersion: 1

datasources:
  # Prometheus Data Source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      # Align with prometheus.yml scrape_interval
      timeInterval: '15s'
      queryTimeout: '30s'
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: x-ray

  # CloudWatch Data Source
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: default
      defaultRegion: us-east-1
      # IAM role for Grafana CloudWatch access
      assumeRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/GrafanaCloudWatchRole
      # Custom namespace for Mint Clone metrics
      customMetricsNamespaces: MintClone
      # Timeout for log queries
      logsTimeout: '30'
      # EKS log groups to monitor
      logGroups:
        - name: /aws/eks/mint-clone/*
          region: us-east-1
    version: 1
    editable: true
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

  # X-Ray Data Source for distributed tracing
  - name: X-Ray
    type: grafana-x-ray-datasource
    access: proxy
    jsonData:
      authType: default
      defaultRegion: us-east-1
      # IAM role for Grafana X-Ray access
      assumeRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/GrafanaXRayRole
      # Service name for tracing
      tracingServiceName: mint-clone
      # Sampling rate for traces
      samplingRate: 0.1
    version: 1
    editable: true
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}