# Prometheus Helm Values Configuration v2.45.0
# Customized for Mint Clone Application Monitoring

nameOverride: "mint-prometheus"
fullnameOverride: "mint-prometheus"

prometheus:
  enabled: true
  replicaCount: 2
  
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  
  retention: "15d"
  retentionSize: "50GB"
  
  persistence:
    enabled: true
    size: "50Gi"
    storageClass: "gp2"
  
  configMapReload:
    prometheus:
      enabled: true
  
  config:
    global:
      scrape_interval: "15s"
      evaluation_interval: "15s"
      scrape_timeout: "10s"
      external_labels:
        environment: "production"
        region: "us-east-1"
  
  serviceMonitors:
    - name: "api-gateway"
      endpoints:
        - port: "http"
          path: "/metrics"
          interval: "15s"
      selector:
        matchLabels:
          app: "api-gateway"
    
    - name: "auth-service"
      endpoints:
        - port: "http"
          path: "/metrics"
          interval: "15s"
      selector:
        matchLabels:
          app: "auth-service"
    
    - name: "account-service"
      endpoints:
        - port: "http"
          path: "/metrics"
          interval: "15s"
      selector:
        matchLabels:
          app: "account-service"
    
    - name: "transaction-service"
      endpoints:
        - port: "http"
          path: "/metrics"
          interval: "15s"
      selector:
        matchLabels:
          app: "transaction-service"
    
    - name: "budget-service"
      endpoints:
        - port: "http"
          path: "/metrics"
          interval: "15s"
      selector:
        matchLabels:
          app: "budget-service"
    
    - name: "investment-service"
      endpoints:
        - port: "http"
          path: "/metrics"
          interval: "15s"
      selector:
        matchLabels:
          app: "investment-service"
  
  alerting:
    enabled: true
    alertmanagers:
      - name: "mint-alertmanager"
        namespace: "monitoring"
        port: 9093
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - "prometheus.mint-clone.com"
    tls:
      - secretName: "prometheus-tls"
        hosts:
          - "prometheus.mint-clone.com"