# Prometheus Configuration v2.45.0
# Global configuration for all monitoring targets
global:
  scrape_interval: 15s     # Default interval for scraping metrics
  evaluation_interval: 15s  # Default interval for evaluating rules
  scrape_timeout: 10s      # Timeout for individual scrape requests
  external_labels:         # Labels added to any time series or alerts
    environment: production
    region: us-east-1

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Rules files to load
rule_files:
  - "/etc/prometheus/rules/*.rules.yml"

# Scrape configurations for monitoring targets
scrape_configs:
  # API Gateway monitoring
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(http_requests_total|http_request_duration_seconds|http_request_size_bytes)'
        action: 'keep'

  # Authentication Service monitoring
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8081']
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(auth_requests_total|auth_failures_total|active_sessions)'
        action: 'keep'

  # Account Service monitoring
  - job_name: 'account-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['account-service:8082']
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(account_operations_total|plaid_api_requests|account_sync_duration_seconds)'
        action: 'keep'

  # Transaction Service monitoring
  - job_name: 'transaction-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['transaction-service:8083']
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(transaction_processing_duration_seconds|categorization_accuracy|transaction_volume)'
        action: 'keep'

  # Budget Service monitoring
  - job_name: 'budget-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['budget-service:8084']
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(budget_updates_total|alert_triggers_total|calculation_duration_seconds)'
        action: 'keep'

  # Investment Service monitoring
  - job_name: 'investment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['investment-service:8085']
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(portfolio_updates_total|market_data_requests|calculation_errors)'
        action: 'keep'

  # Node Exporter for host metrics
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']

  # Kubernetes service discovery
  - job_name: 'kubernetes-service-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: ['__meta_kubernetes_service_annotation_prometheus_io_scrape']
        action: 'keep'
        regex: true